#!/bin/bash

set -ex

echo `pwd`
echo 'abba'

./scripts/version_bump

bundle

gem build ish_models.gemspec
gem push ish_models-`cat VERSION`.gem

git add .
git commit -m 'autobuild `date "+%Y%m%d"`'
git push

echo "ish_models build ok"
