#!/bin/bash

set -x

if ! (( ssh-add -L | grep mac_id_rsa )) ; then
  ssh-add ~/.ssh/mac_id_rsa
fi

./scripts/version_bump &&
version=`cat VERSION`
cat ish_models.gemspec-template | \
  sed -e "s/\$version/$version/g" > ish_models.gemspec

bundle &&

gem build ish_models.gemspec &&
gem push ish_models-`cat VERSION`.gem &&

git add . &&
git commit -m 'autobuild `date "+%Y%m%d"`' ;
git push &&

echo "ish_models build ok"
