---

- name: create buckets
  community.docker.docker_container_exec:
    - container: localstack
    - command: awslocal s3 mb s3://wco-email-development

- name: create buckets
  community.docker.docker_container_exec:
    - container: localstack
    - command: awslocal s3 mb s3://wco-email-ses-development

# - name: create one message_stub
